# Generated by Django 3.1.2 on 2022-01-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('collage_name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('collages_type', models.CharField(choices=[('BCA', 'bca'), ('BE', 'be'), ('BA', 'ba')], max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
