# Generated by Django 3.1.2 on 2022-01-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collages',
            name='collages_type',
            field=models.CharField(choices=[('bca', 'bca'), ('be', 'be'), ('ba', 'ba')], max_length=50),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('student_name', models.CharField(max_length=20)),
                ('student_roll_no', models.IntegerField()),
                ('student_admission_year', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('school_student', 'school_student'), ('collage_student', 'collage_student')], max_length=20)),
                ('student_stream', models.CharField(choices=[('information_technology', 'information_technology'), ('computer_science', 'computer_science'), ('electrical_engineering', 'electrical_engineering'), ('electronic & communication', 'electronic & communication')], max_length=50)),
                ('student_std', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=20)),
                ('student_address', models.TextField()),
                ('collage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.collages')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
