# Generated by Django 3.1.2 on 2022-01-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220118_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_stream',
        ),
    ]
