# Generated by Django 3.1.2 on 2022-01-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_student_student_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_std',
        ),
    ]
