# Generated by Django 3.1.2 on 2022-01-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_student_student_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_address',
            field=models.CharField(max_length=50),
        ),
    ]
