# Generated by Django 3.1.2 on 2022-01-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_number',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
