# Generated by Django 3.1.2 on 2022-01-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_course_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
    ]
